# Generated by Django 4.2 on 2024-03-19 07:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='bookmarked_users',
            field=models.ManyToManyField(related_name='bookmarked_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
